<a href="https://colab.research.google.com/github/hadimoussavi/MyCookbook/blob/master/Linalg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a = np.array([[3,1],[1,2]])
b = np.array([9,8])
np.linalg.solve(a,b)

array([2., 3.])

In [5]:
x = np.array([[6,2,-5],[3,3,-2],[7,5,-3]])
y = np.array([13,13,26])
np.linalg.solve(x,y)

array([2., 3., 1.])

In [6]:
a= np.array([[1,2],[3,4]])
np.linalg.matrix_power(a,2)

array([[ 7, 10],
       [15, 22]])

In [7]:
np.dot(a,a)

array([[ 7, 10],
       [15, 22]])

In [8]:
np.linalg.matrix_power(a,3)

array([[ 37,  54],
       [ 81, 118]])

In [9]:
np.linalg.matrix_power(a,0)

array([[1, 0],
       [0, 1]])

In [10]:
np.linalg.matrix_power(a,-2)

array([[ 5.5 , -2.5 ],
       [-3.75,  1.75]])

In [11]:
b = np.linalg.inv(a)
b

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [12]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [13]:
b = np.linalg.inv(a)
b

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [15]:
np.allclose(np.dot(a,b),np.eye(2))

True

In [16]:
np.dot(a,b)

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [17]:
help(np.linalg.inv)

Help on function inv in module numpy.linalg:

inv(a)
    Compute the (multiplicative) inverse of a matrix.
    
    Given a square matrix `a`, return the matrix `ainv` satisfying
    ``dot(a, ainv) = dot(ainv, a) = eye(a.shape[0])``.
    
    Parameters
    ----------
    a : (..., M, M) array_like
        Matrix to be inverted.
    
    Returns
    -------
    ainv : (..., M, M) ndarray or matrix
        (Multiplicative) inverse of the matrix `a`.
    
    Raises
    ------
    LinAlgError
        If `a` is not square or inversion fails.
    
    Notes
    -----
    
    .. versionadded:: 1.8.0
    
    Broadcasting rules apply, see the `numpy.linalg` documentation for
    details.
    
    Examples
    --------
    >>> from numpy.linalg import inv
    >>> a = np.array([[1., 2.], [3., 4.]])
    >>> ainv = inv(a)
    >>> np.allclose(np.dot(a, ainv), np.eye(2))
    True
    >>> np.allclose(np.dot(ainv, a), np.eye(2))
    True
    
    If a is a matrix object, then the return value is a 